server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario
          uri: lb://usuario
          predicates:
            - Path=/usuario/**
        - id: coche
          uri: lb://coche
          predicates:
            - Path=/coche/**
        - id: moto
          uri: lb://moto
          predicates:
            - Path=/moto/**
