server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/SamuelIsip/microservicios-spring
          search-paths: config-data
  application:
    name: config-services